name: taariq
version: 0.1.0
description: taar.iq website and blog
author: Taariq Mullins
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  js: ^0.6.1
  vue: any
dependency_overrides:
  vue:
    path: ../vue
dev_dependencies:
  build_runner: 0.10.1
  build_web_compilers: any
  livereload: ^0.4.1