name: taariq
version: 0.1.0
description: taariq website and blog
author: Taariq Mullins
dependencies:
  js: ^0.6.1
dependency_overrides:
  vue:
    path: ../vue
dev_dependencies:
  build_runner: 0.10.1
  build_web_compilers: any